REM You can increase the number of clients by repeating start ExecuteClient.cmd
SET SUBDIR=%~dp0

start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
start %SUBDIR%ExecuteClient.cmd
exit
